name: my-alist
services:
  alist:
    image: alist666/alist:latest
    container_name: alist
    network_mode: bridge
    ports:
      - target: 5244
        published: "5244"
        protocol: tcp
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - type: bind
        source: /home/orangepi/alist
        target: /opt/alist/data
    x-casaos:
      ports:
        - container: "5244"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
      volumes:
        - container: /opt/alist/data
          description:
            en_us: alist config directory.
            zh_cn: alist 配置目录
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: asxs
  category: myappstore
  description:
    en_us: |
      Access your remote cloud files as if they were local files using Alist.
    zh_cn: |
      使用 Alist 像访问本地文件一样访问你远程网盘的文件，
  developer: Xhofe
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Alist/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Alist/screenshot-1.png
  main: alist
  port_map: "5244"
  scheme: http
  tagline:
    en_us: A file list program that supports multiple storage
    zh_cn: 一个支持多种存储的文件列表程序
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Alist/thumbnail.png
  tips:
    before_install:
      en_us: After installation, please check the initial password in the container log (Settings - TopRight - Terminal and Logs - Logs).
      zh_cn: 安装完成后，请在容器日志（应用-设置-右上角-终端与日志-日志）中查看初始密码。
  title:
    en_us: Alist
